### ISSUE TITLE
Object Viewer QT world editor plugin crash

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#108]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/108) by Meelis Mägi (Bitbucket: [Meelis Mägi](https://bitbucket.org/Meelis Mägi), ).**

----------------------------------------

```
#0  0x00007ffff5fe1f77 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5fe55e8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7b35055 in NLMISC::CClassRegistry::registerClass (className=..., creator=0x7fffda798bf0 <NLLIGO::CPropertyString::creator()>, 
    typeidCheck=...) at /srv/shard/nel/src/misc/class_registry.cpp:86
#3  0x00007fffda7935bc in NLLIGO::Register () at /srv/shard/nel/src/ligo/primitive.cpp:2743
#4  0x00007fffd8b9ba82 in WorldEditor::WorldEditorPlugin::initialize (this=0x8945f0, pluginManager=<optimized out>, errorString=0x7fffffffdd60)
    at /srv/shard/nel/tools/3d/object_viewer_qt/src/plugins/world_editor/world_editor_plugin.cpp:68
#5  0x0000000000409b71 in ExtensionSystem::PluginSpec::initializePlugin (this=0x8052f0)
    at /srv/shard/nel/tools/3d/object_viewer_qt/src/extension_system/plugin_spec.cpp:378
#6  0x000000000040da78 in ExtensionSystem::PluginManager::setPluginState (this=<optimized out>, spec=0x8052f0, destState=5)
    at /srv/shard/nel/tools/3d/object_viewer_qt/src/extension_system/plugin_manager.cpp:245
#7  0x000000000040e977 in ExtensionSystem::PluginManager::loadPlugins (this=0x7fffffffdf10)
    at /srv/shard/nel/tools/3d/object_viewer_qt/src/extension_system/plugin_manager.cpp:100
#8  0x000000000040885b in main (argc=1, argv=<optimized out>) at /srv/shard/nel/tools/3d/object_viewer_qt/src/main.cpp:173
```

If I disable NLLIGO::Register() in world_editor_plugin.cpp line 68, then it starts.

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

This has already been fixed.
