### ISSUE TITLE
ams latest ticket

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#111]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/111) by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

when there are no tickets it throws an error

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ryzom_ams_lib`.`ticket_log`, CONSTRAINT `fk_ticket_log_ticket1` FOREIGN KEY (`Ticket`) REFERENCES `ticket` (`TId`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/ams_lib/autoload/dblayer.php:66 Stack trace: #0 /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/ams_lib/autoload/dblayer.php(66): PDOStatement->execute(Array) #1 /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/ams_lib/autoload/ticket_log.php(87): DBLayer->execute('INSERT INTO tic...', Array) #2 /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/www/html/inc/show_ticket.php(48): Ticket_Log::createLogEntry('', '1', 3) #3 /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/www/html/index.php(91): show_ticket() #4 {main} thrown in /home/default/development/ryzom/code/ryzom/tools/server/ryzom_ams/ams_lib/autoload/dblayer.php on line 66

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Issue #126 was marked as a duplicate of this issue.

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

Fix #111
