### ISSUE TITLE
AMS Error when clicking on 'Newest ticket' on new install

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#126]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/126) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Clicking on 'Newest Ticket' on a new installation (with no tickets), gives the following error

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (temp file operation failed)' in /srv/data/web/vhosts/---/ams_lib/autoload/dblayer.php:66 Stack trace: #0 /srv/data/web/vhosts/---/ams_lib/autoload/dblayer.php(66): PDOStatement->execute(Array) #1 /srv/data/web/vhosts/---/ams_lib/autoload/ticket_log.php(87): DBLayer->execute('INSERT INTO tic...', Array) #2 /srv/data/web/vhosts/---/htdocs/inc/show_ticket.php(48): Ticket_Log::createLogEntry('', '2', 3) #3 /srv/data/web/vhosts/---/htdocs/index.php(91): show_ticket() #4 {main} thrown in /srv/data/web/vhosts/---/ams_lib/autoload/dblayer.php on line 66

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Duplicate of #111.
