### ISSUE TITLE
AMS does not load to homepage when shard servers are down

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#200]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/200) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Fatal error: Uncaught exception 'PDOException' with message 'Failed to connect to the 'shard' database server' in /srv/data/web/vhosts/*/private_php/ams/autoload/dblayer.php:81 Stack trace: #0 /srv/data/web/vhosts/*/private_php/ams/plugins/Domain_Management/Domain_Management.php(70): DBLayer->__construct('shard') #1 [internal function]: domain_management_hook_get_db() #2 /srv/data/web/vhosts/*/private_php/ams/autoload/plugincache.php(270): call_user_func('domain_manageme...') #3 /srv/data/web/vhosts/*/htdocs/ams/index.php(144): Plugincache::loadHooks() #4 {main} thrown in /srv/data/web/vhosts/*/private_php/ams/autoload/dblayer.php on line 81

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

FIX #200

dont crash when neldb is missing

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Why is it connecting to the nel database on the homepage?
